name: Build, Zip and Notify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Confirm dist folder exists
        run: ls -la dist

      - name: Zip dist folder
        run: |
          zip -r dist.zip dist
          ls -lh dist.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist.zip

      - name: Send Webhook
        run: |
          curl -X GET \
            "${{ secrets.WEBHOOK_URL }}"
